### ISSUE TITLE
updateDefaultFBO is run twice at startup

### ISSUE THREAD

**Issue by bryan05** [NVIDIAGameWorks/Falcor#105]
the first is Sample::runInternal ->Device::create -> Device::init ->updateDefaultFBO
the second is Window::msgLoop ->Sample::handleWindowSizeChange -> Device::resizeSwapChain  ->updateDefaultFBO.
this caused mpApiData->pSwapChain->GetBuffer(i, IID_PPV_ARGS(&apiHandles[i])) is run twice. I checked the array apiHandles.
If I only run the first updateDefaultFBO , when i resize the window, I got the error.

> DXGI ERROR: IDXGISwapChain::ResizeBuffers: Swapchain cannot be resized unless all outstanding buffer references have been released. [ MISCELLANEOUS ERROR #19: ]

after I added the following code in Device::resizeSwapChain, the error is gone
```
        for (uint32_t i = 0; i < mSwapChainBufferCount; i++)
        {
	mpSwapChainFbos[i]->getColorTexture(0)->mApiHandle.Release();
        }
```
I tried to add a data breakpoint for mApiHandle, but it doesn't work. is this handle automatically released?

**Comment by bryan05** [comment]
If I only run the first and second updateDefaultFBO ,there is no error

**Comment by nbenty** [comment]
You shouldn't release API handles yourself, the framework handle that.
I'm not sure what error you are reporting - everything works fine on our test machines.

`resizeSwapChain` is called twice, it's a known issue which doesn't really affect anything. 
- We have to call `onResizeSwapChain()` after `onLoad()`
- Windows sends a WM_RESIZE message once we start the message loop.
I used to filter the second resize but removed it at some point since the code was ugly and calling resize twice shouldn't affect anything

**Comment by bryan05** [comment]
thanks to letting me know
