### ISSUE TITLE
InterlockedAdd failed to compile on vulkan

### ISSUE THREAD

**Issue by KaChen-Dex** [NVIDIAGameWorks/Falcor#135]
Hi,
InterlockedAdd can't be compiled on linux with vulkan. Please see below.

`RWTexture2D<uint> gGridSegmentationCountTex0;
uint prevValue = 0;
InterlockedAdd(gGridSegmentationCountTex0[mapIntCoord], 1u, prevValue);`

Would appreciate for a quick fix. thanks!

**Comment by KaChen3000** [comment]
the error message:

Program Linkage failed.

Program with Shaders:

(119): error 40008: the form of this l-value argument is not valid for a `ref` parameter

**Comment by tfoleyNV** [comment]
This probably needs to be filed as an issue against Slang instead.

I wouldn't be able to look at this until Monday at the earliest, but even then I'm concerned that it won't be a quick fix to get this working correctly with the HLSL syntax in your example. I can try to add the missing support but I'd estimate at least 2-3 days to do it right.

As a temporary workaround (please understand that I'm not promising Slang will support this in the long run), could you try defining a function like the following:

```hlsl
__target_intrinsic(glsl, "imageAtomicAdd($0, $1, $2)$z")
uint imageAtomicAdd(RWTexture2D<uint> t, int2 coord, uint val)
{
    uint prevVal = 0;
    InterlockedAdd(t[coord], val, prevVal);
    return prevVal;
} 
```

I haven't tested the above, so I may have made some mistakes, but something like this should work to define a custom GLSL lowering for a function. I'll repeat that this is *not* intended to be something that Slang supports in the long term.

Worst case I could add a function along the lines of the above to the Slang standard library so that you can access image atomics on both D3D and Vulkan, even if the syntax isn't the standard HLSL syntax.

**Comment by tfoleyNV** [comment]
Okay, I gave the above a quick test and it doesn't quite work as written, but the following should work for both D3D and Vulkan targets:

```hlsl
__target_intrinsic(glsl, "($3 = imageAtomicAdd($0, $1, $2)$z)")
__target_intrinsic(hlsl, "InterlockedAdd($0[$1], $2, $3)")
void imageAtomicAdd(RWTexture2D<uint> t, int2 coord, uint val, out uint prevVal);
```

I can try to add a set of operations along these lines to the Slang standard library early next week to cover the main image atomic cases. Adding support for the proper HLSL syntax will take a bit longer.

**Comment by KaChen3000** [comment]
thank you very much for quick answer. i will try that.

**Comment by kyaoNV** [comment]
Falcor 3.1 has updated 0.11.4. The error I'm seeing now in Vulkan is:
`imageAtomicAdd: no matching overloaded function found`
`assign: cannot convert from 'const float' to 'temp highp uint'`
