### ISSUE TITLE
error X3000: unrecognized identifier '__import'

### ISSUE THREAD

**Issue by manoyes** [NVIDIAGameWorks/Falcor#161]
Running on Windows Visual Studio 2017. Building the `StereoRendering` project works. Duplicating `StereoRendering.ps.hlsl` into another hlsl file and adding to the Data filter results in a failed build with the error: 

```
1>------ Build started: Project: FalcorSharedObjects, Configuration: DebugD3D12 x64 ------
1>Processing project file 'F:\Repositories\Falcor\dependencies.xml'
1>FalcorSharedObjects.vcxproj -> F:\Repositories\Falcor\Bin\x64\Debug\FalcorSharedObjects.dll
2>------ Build started: Project: Falcor, Configuration: DebugD3D12 x64 ------
2>Falcor.vcxproj -> F:\Repositories\Falcor\Bin\Int\x64\DebugD3D12\Lib\Falcor.lib
3>------ Build started: Project: StereoRendering, Configuration: Debug x64 ------
3>F:\Repositories\Falcor\Samples\Core\StereoRendering\Data\Test.ps.hlsl(28,1-8): error X3000: unrecognized identifier '__import'
3>
3>compilation failed; no code produced
3>Done building project "StereoRendering.vcxproj" -- FAILED.
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

It's the exact same shader code, so it's not clear why the `__import` identifier breaks in a different file.

**Comment by tfoleyNV** [comment]
By default, Visual Studio assumes that any `.hlsl` files added to a project should be compiled offline to bytecode using fxc. That isn't appropriate for Falcor where all of the shader files are loaded at run-time, and use our extended Slang shading language.

Using the Visual Studio build settings you should be able to get to the properties by right-clicking on your new `.hlsl` file and set "Excluded From Build" to "Yes".

This kind of problem can be avoided by using a `.slang` extension for shader files instead of `.hlsl`, because then Visual Studio doesn't over-zealously assume it knows how to build them, but the trade-off in that case is that you may not get useful syntax highlighting in your shader code.
