### ISSUE TITLE
how to enable VideoDecoder?

### ISSUE THREAD

**Issue by 625673575** [NVIDIAGameWorks/Falcor#176]
Im currently working on post process,and I want to simply the input by enable video input  as dynamic texture,but it seems disable by original commit ,and I have no idea how to enable it again.

**Comment by 625673575** [comment]
I hope you can fixed it back to available.I am really need this function .

**Comment by nbenty** [comment]
This feature was deprecated a long time ago. We disabled it because FFMPEG made breaking changes to their API.
It was used to replay videos, it wasn't good for dynamic texturing - it did the decoding right before the texture was needed and was blocking the pipeline.

I'd like to correctly support it, but I can't tell when we'll implement it.

**Comment by 625673575** [comment]
@nbenty OK,I am looking forward to your implementation,the frames could read hundreds frames as buffers in another thread,so it won't block the pipeline continuously,this framework is really awesome and helpful,I use it to do research things,and I also have added new function to some Helper class ,so is it ok for me to push these changes to this repository?like read Texture2DArray from different image files or from a gif file.
