### ISSUE TITLE
ProgramVars::getParameterBlock() returns SharedConstPtr

### ISSUE THREAD

**Issue by philcn** [NVIDIAGameWorks/Falcor#184]
Hi, I'm confused about the ProgramVars::getParameterBlock() returning a ParameterBlock::SharedConstPtr. Is this a typo, or does Falcor not encourage mutating the parameter block owned by the program vars and wants users to always assign a new parameter block?

**Comment by nbenty** [comment]
That's intentional.
`ParameterBlock`s are not allocated by `ProgramVars`. They are allocated and attached to vars by the user, and in some cases internal systems.

Since the `ProgramVars` object is attached to the state, other parts of the code which do not own the `ParameterBlock` have access to it, and we chose to restrict that access.

Note that C++ `const` is just a recommendation - it's there to say "you shouldn't change that object", not "you can't change the object". If you know what you're doing, feel free to `const_cast` it and change the block.

We're making some changes to Falcor where the state will no longer store the vars. Once that happens the only way to share `ProgramVars` will be by explicitly moving them around. Once that change happens, I'll remove the `ParameterBlock` constness
