### ISSUE TITLE
Avoiding runtime shader compilation, or reducing its cost

### ISSUE THREAD

**Issue by emxaz** [NVIDIAGameWorks/Falcor#225]
In our project, we are seeing that runtime shader compilation is contributing in a major way to our application's initial startup time. Specifically, the cost of `spCompile` is very high, and that function by itself dwarfs all other aspects of our application's startup. We are targeting SPIR-V, and on average we trigger `spCompile` (which I understand maps 1:1 with a unique, used-at-runtime shader variant) 100 times. Now, there are a few ways to mitigate this, but I don't see a very clear or optimal solution. Some things that are possible:
* Try to reduce the number of shader variants being used. This is difficult and could have widespread effects, such as the runtime performance of the refactored shaders.
* Try to reduce the number of duplicate shaders (e.g. identical variants) by caching instances in our project's code. However, this does not catch duplicates generated by Falcor, e.g. when instantiating multiple `Picking` instances, each compiles its own duplicate shader variants.
* Try to manipulate the compilation options so that each invocation is less expensive. It's unclear that any settings we change will significantly impact compilation time. We are using the default optimization level currently, but ideally we would actually be using a more aggressive and presumably expensive optimization level.

In general, what I see is that the shader compilation process itself is just too expensive for us to do it at runtime. Each call to `spCompile` takes around 60-300 ms, which very quickly adds up. It would be very desirable if shader compilation could happen offline, or if some of the cost of runtime compilation could be avoided or mitigated. Is anything like this supported currently, or planned for 4.0? Some potential features that I am thinking about:
* The ability to load a `Program` directly from bytecode[+serialized metadata]. This could be produced using a Falcor-provided tool, or left to the user if the expected format was well-defined.
* The ability to save the bytecode[+serialized metadata] from a runtime-compiled Program instance. If offline tooling was not available, we could still persist the generated bytecode at runtime, to improve the startup time of subsequent launches.

There are related topics that I have been mulling over, such as the ability to use a VkPipelineCache to further improve shader loading time.  But from what I have seen, the slang compilation process by itself is the single major blocker for us currently.

**Comment by tfoleyNV** [comment]
The overhead of `spCompile` comes from multiple steps in the Slang compiler stack, which includes generating GLSL and then invoking the Khronos glslang compiler to produce SPIR-V (and in recent builds of Slang, to also run some optimization passes on that SPIR-V). It is unlikely that we will be able to make changes that produce order-of-magnitude differences in the shader compile times you are seeing just from optimizing the code behind `spCompile`.

As you've identified, your best bet is to either reduce the number of times `spCompile` gets invoked at runtime or to find a path for loading shader code from disk.

Having support for a shader cache using serialized compilation results would be interesting, and is something we've wanted to support through the Slang API. Unfortunately, this is unlikely to be something that gets implemented soon unless somebody in the community wants to contribute their time to it.

It is a long-term goal for the Slang project to allow serializiation and deserialization of compilation results (both the bytecode and reflection data) which could provide the basis for a shader caching layer in Falcor, but that work is unlikely to happen any time soon. Trying to do serialization/deserialization entirely in the Falcor code might be possible on a Falcor 3.x branch, but the Falcor 4.x code will have Slang more tightly integrated so that
