### ISSUE TITLE
Shader::CompilerFlags::GenerateDebugInfo not generating additional shader .pdb file

### ISSUE THREAD

**Issue by TheGoozah** [NVIDIAGameWorks/Falcor#265]
Hi all,

I would like to perform some shader debugging using PIX, but I am currently unable to find .pdb generation support for shader files in Falcor. When I pass the Shader::CompilerFlags::GenerateDebugInfo, no additional symbols are getting exported.

Not sure if I am overlooking something, or if the support is just not there. If it isn't supported, any idea how to do this properly?

Thank you in advance!

**Comment by tfoleyNV** [comment]
Some of the `CompilerFlags` supported by Falcor may have stopped working due to changes in the way Falcor talks to the Slang shader translator that it uses.

I will try to look into the issue next week.

**Comment by TheGoozah** [comment]
@tfoleyNV That would be great as I am currently unable to continue my research in Falcor without proper debugging support. Have a nice week!

**Comment by v007rj** [comment]
@TheGoozah I think that you should use a built version of the Unity application that you are using to capture frames, rather than a version running in the Unity Editor. This is because you need to launch the target application from within PIX to capture GPU frames. Try using development build features as they add additional information to PIX, which makes navigating the scene
 capture easier.
