### ISSUE TITLE
bistro scene  rendering problem

### ISSUE THREAD

**Issue by pure-water** [NVIDIAGameWorks/Falcor#324]
Hi, 
  Has any one trid loading the bistro scene (https://developer.nvidia.com/orca/amazon-lumberyard-bistro) here?  I can make it run actually but still a few questions. 

  Is the scene supposed to be rended on a g-buffer (deferred) pipeline? I  tried the forward_render.py at the falcor . It does not get teh correct results. 

 Why the back face shading normal seems to be temp related. I can see a few glittcher. 

Regards

**Comment by skallweitNV** [comment]
The raster lighting pipeline is something that has been in fairly broken state for a long time. Falcor fully focuses on path tracing these days. The next update will actually remove most of the raster code (only GBuffer/VBuffer passes will be still available in raster).

**Comment by mohammedari** [comment]
Hello, @skallweitNV 

Is that a decision that cannot be changed?

I recently spent some time fixing the flickering issue in the Bistro scene, which is also mentioned in this issue ( https://github.com/NVIDIAGameWorks/Falcor/issues/277 ), and finally found a float-point precision error causes the issue in CSM pass.

I will make a pull request to fix the problem in CSM anyway, but is there any chance to keep the raster passes maintained by the community? I hope we can continue using the Falcor framework in projects using raster pipelines.

**Comment by skallweitNV** [comment]
Hi @mohammedari 

This decision has been made because our research focus is fully set on path tracing and we don't have the resources to support the rasterization path (hence it was broken for so long). Also, the raster code was really far from state-of-the-art, so it wasn't even useful as the basis for any kind of research in that area. That being said, rasterization is still supported on the API level (and will be moving forward), but if you want to do rasterization based rendering you will have to maintain your own render passes in a fork. Sorry about that, but I hope you do understand the decision we've made given the context here.

**Comment by mohammedari** [comment]
Thank you for the response @skallweitNV. 
I understand the situation. I would make another repository to maintain the obsolete raster passes once the next version is released.

I made a PR mainly for the reference purpose who want to use the raster pipeline, but it also contains a fix in Raster.slang to make a more stable result in a large scene. So it also may affect GBuffer/VBuffer passes that are continued to support. I would appreciate it if you kindly review the PR.
