### ISSUE TITLE
Interface for the transformation of shapes

### ISSUE THREAD

**Issue by swordigo1995** [NVIDIAGameWorks/Falcor#354]
Hi,
I plan to use Falcor to generate a dataset with fully randomized scenes, and I find it to be a great choice since it provides interfaces in 'falcor.Scene' like `cameras`, `lights`, and `materials`. I can easily access and modify these scene attributes in the script. However, I noticed that there is no interface for the transformation of shapes. So, I wonder if there are any crucial difficulties in implementing this. Is it possible to implement an interface to access shapes and modify their transformation in the script, or modify transformation through GUI in real-time path tracing? Any advice would be greatly appreciated.

**Comment by skallweitNV** [comment]
Hi, unfortunately the current state with scene graph manipulation is a bit more difficult, that's why we never exposed it. So the issue is that when scenes are imported, we don't fully preserve the scene graph to make rendering more efficient. There are flags you can set to disable the scene optimizations, which _should_ preserve the scene graph. We also do not preserve a good data structure to maintain the hierarchical scene graph. It's all just managed through parent node IDs. So the easiest/hacky way to go about this would be to allow access to local transformation matrices through node IDs and have a way to enumerate all geometry instances in the scene.

We are currently reworking the scene data structure to allow dynamic editing of scenes. We are also expanding the python bindings a lot to allow much more to be controlled from python. But I cannot give you any timeline on when these new features will become available in the public version.

**Comment by swordigo1995** [comment]
Thanks for your response. It's really helpful.
