### ISSUE TITLE
403 Forbidden Error On Required Dependencies in Falcor 7

### ISSUE THREAD

**Issue by slayyden** [NVIDIAGameWorks/Falcor#443]
I am attempting to build Falcor on Windows. Upon running `setup.bat`, the following error occurs:

`Package 'python' at version '3.10.11+nv1-windows-x86_64' is missing from local storage.
packman(ERROR): Unable to download file from 'https://d4i3qtqj3r0z5.cloudfront.net/python%403.10.11%2Bnv1-windows-x86_64' (server returned 403)`

After attempting to install Python manually, I encountered another 403 error:

`Package 'cmake' at version '3.22.1+nv1-windows-x86_64' is missing from local storage.
packman(ERROR): Unable to download file from 'https://d4i3qtqj3r0z5.cloudfront.net/cmake%403.22.1%2Bnv1-windows-x86_64' (server returned 403)`

Would it be possible to ensure these links work? If not, how do I ensure that I correctly install the dependencies manually?

**Comment by TheOwlforge** [comment]
I had the same problem. The solution from issue 424 (https://github.com/NVIDIAGameWorks/Falcor/issues/424) worked for me: Navigate to _Falcor\tools\packman_ or _Falcor\Build\packman_ on older versions and run `packman update` or `./packman.cmd update`.

**Comment by bipul-mohanto** [comment]
Hi @slayyden, I am facing the same error with `Falcor-3.2.1`, error message [details](https://github.com/NVIDIAGameWorks/Falcor/issues/424#issuecomment-2340056557) under issue #424. Unfortunately `packman update` doesn't work for this version as there is no `update` option. Any suggestion?

**Comment by slayyden** [comment]
`packman update` worked for me. Unfortunately I do not know of any other fixes.

**Comment by bipul-mohanto** [comment]
Thanks @slayyden for the reply. Probably you have used a higher version than `3.2.1`, because I can see (`packman update`) the update option in `Falcor 8.0`. Unfortunately, the version I am trying to exploit has only ```usage: packman [--version] [-h]
               {cache,help,install,list,pack,publish,push,pull,verify,run,remotes,hash,project}```. Above all, the link `https://d4i3qtqj3r0z5.cloudfront.net/dxcompiler%4010.0.17763.0` is broken. My guess, is this is the problem. Trying to get support from the Falcor team.

**Comment by tomas-davidovic** [comment]
This could be for couple reasons, most of them out of our control. The packman publishing process has been adjusted last year for security reasons. This required new packman version to work on existing packages, and also turned making packages public into a much more formal process. I also believe some of the repositories have been completely removed.

It is possible that the old packman simply no longer works. What you can do is check out the newest Falcor and copy over the `tools/packman` directory with the newest packman version into your existing `3.2.1` checkout. If that doesn't fix the issue, then look into the `dependencies.xml` of your version and the `8.0` in case there the remote has changed. We also internalized some libraries that have previously been downloaded via packman (`sobol` is one of those). If this doesn't lead anywhere, I will consult next week with my colleagues, but since packman policies are not really in our control, I cannot promise any clean solution.

**Comment by bipul-mohanto** [comment]
Thanks a lot, @tomas-davidovic, copying from Falcor 8.0 solved the problem. Did not need `dependencies.xml` replacement. Just out of curiosity, is `packman` Nvidia's in-house package manager like vcpkg/conan?

**Comment by tomas-davidovic** [comment]
Awesome, glad it worked for you! And yeah, it is an in-house package system. I think it is much simpler than vcpkg at least. It pretty much just manages any blobs of data we want to store in a versioned fashion on fast storage. So sometimes it distributes binaries (like `cmake` or `python`) but we also use it to distribute the test scenes (`falcor_media`). The system has no stake in where the data comes from. I belive both alternatives you mentioned are more focused on software packages.
