### ISSUE TITLE
Feature Request: DLL build of Falcor

### ISSUE THREAD

**Issue by Alekssasho** [NVIDIAGameWorks/Falcor#70]
Are there any plans for supporting a DLL build of Falcor ?

I want to do hot reloading of render loop code, so there is no need to shut down the application every time  some c++ code inside the render loop is changed, as loading whole models and scene is somewhat slow, especially the ORCA scenes.
My setup is an application which has holds the Falcor::Renderer instance and is handling rendering code dll hot reloading. It is forwarding onFrameRender and onGuiRender calls to the rendering code DLL.
There is a DLL which holds function for initializing some state, and onFrameRender and onGuiRender calls which implement the main render logic.

The problem right now is Falcor is statically build and contains some globals which are not properly initialized in the DLL due to not having a Renderer instance. Also there is a duplication of all of the code that way. Having Falcor built as DLL will solve this problems and enable this workflow with hot reloading rendering code.

**Comment by nbenty** [comment]
I need to fix that, but would like to keep Falcor as a static library. The usage model I have in mind is:
- Falcor will have a `DynamicRenderer` sample, which is basically a simple `Renderer` which renders nothing except for a GUI with a `Load DLL` button.
- The user implements a `Renderer` in a DLL which can be loaded by the sample. Once that DLL is loaded, all the callbacks will be redirected to it.
- The `DynamicRenderer` renderer can hold a `Scene` to avoid asset reloading when switching renderers.

I'm not sure I need to change `Sample` since `Renderer` doesn't inherit from it.

**Comment by Alekssasho** [comment]
So the plans are to fix all global variables so that Falcor being a statically linked can be used from both DLLs safely. 
Do you have any estimate when this could happen ?

**Comment by nbenty** [comment]
Hopefully this week

**Comment by Alekssasho** [comment]
That sound awesome.
I will close the issue then, as there will be a solution soon.
