### ISSUE TITLE
Texture2DMS isn't recognized by the slang

### ISSUE THREAD

**Issue by bryan05** [NVIDIAGameWorks/Falcor#74]
I encounter an error:
my shader code is like this:
Texture2DMS<float4,2> s_texture_0 : register(t0); 

in c++ code its kind is NULL
   ReflectionType::SharedPtr reflectType(TypeLayoutReflection* pSlangType, const ReflectionPath* pPath)
    {
        auto kind = pSlangType->getType()->getKind();

**Comment by tfoleyNV** [comment]
Thanks for reporting this. I’ll look into it.

**Comment by tfoleyNV** [comment]
I think the issue here is that Slang does not support passing an explicit sample count to the `Texture2DMS` type. When I write a stand-alone shader with a declaration like:

```hlsl
Texture2DMS<float4, 2> gTexture;
```

I get an error from the Slang compiler:

```
test.slang(1): error 39999: too many arguments to call (got 2, expected 1)
```

While that error message isn't great, it is accurate because the Slang compiler only expects a single argument for the `Texture2D` generic type. If I rewrite my declaration as follows:

```hlsl
Texture2DMS<float4> gTexture;
```

I find that the shader compiles without error to DXBC for Shader Model 5.0, and in my stand-alone testing the reflection info I get back appears to be valid.

Can you confirm what version of Falcor you are using, and perhaps share a minimal example that reproduces the problem?

**Comment by bryan05** [comment]
I passed  slangFlags |= SLANG_COMPILE_FLAG_NO_CHECKING as the compile flag, so I don't get that error.
after passing single argument for the Texture2D generic type, I get the valid reflection info.

My version is 3.0.
thanks very much
